---
- name: Update apt-get repo and cache
  apt: update_cache=yes

- name: Install packages
  package:
    name: "{{item}}"
    state: present
  loop:
    - git
    - docker.io
    - python3

- name: add user hw20
  user:
    name: hw20
    create_home: yes
    home: /opt/hw20
    state: present

- name: add hw20 to sudo group
  import_tasks: sudoadd.yaml
  when: ifsudo

- name: git clone
  shell: sudo -u hw20 git clone https://github.com/Swordfish90/cool-retro-term.git /opt/hw20/git
