---
- name: create user and keys
  include_tasks: users.yaml
  loop: "{{ users }}"
  tags: user
  when: "users|length <= 3"

- name: update packages
  become: true
  ansible.builtin.yum:
    name: '*'
    state: latest
  tags: update

- name: check if google is accessible
  ansible.builtin.wait_for:
    host: google.com
    port: 80
    state: started
    delay: 0
    timeout: 1

- name: write date to file
  ansible.builtin.copy:
    content: "{{ ansible_date_time.date }}"
    dest: "{{ local_path_to_date }}"
  delegate_to: localhost

- name: copy date to remote
  become: true
  ansible.builtin.copy:
    src: "{{ local_path_to_date }}"
    dest: "{{ remote_path_to_date }}"

- name: install packages from local
  include_tasks: install.yaml
  loop: "{{ packages_list }}"
