---
- name: copy local files to remote
  copy:
    src: "{{copysource}}"
    dest: "{{copypath}}"
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Install curl from deb
  block:
    - name: copy deb package
      copy:
        src: files/curl_7.68.0-1ubuntu2.5_amd64.deb
        dest: /home/vagrant
    - name: install deb package
      become: true
      apt:
        deb: /home/vagrant/curl_7.68.0-1ubuntu2.5_amd64.deb
        state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install curl from rpm
  block:
    - name: copy rpm package
      copy:
        src: files/curl-7.61.1-14.el8_3.1.x86_64.rpm
        dest: /home/vagrant
    - name: install rpm package
      become: true
      yum:
        name: /home/vagrant/curl-7.61.1-14.el8_3.1.x86_64.rpm
        state: present
        disable_gpg_check: yes
  when: ansible_distribution == 'CentOS'

- name: create hw20 file info
  become: true
  template:
    src: templates/hw20.j2
    dest: /HW20_FILE_INFO
