---
- name: copy local files to remote
  copy:
    src: "{{copysource}}"
    dest: "{{copypath}}"
    owner: "{{user_group}}"
    group: "{{user_group}}"
    mode: "{{priviledges}}"

- name: Install curl from deb
  block:
    - name: copy deb package
      copy:
        src: "files/{{deb_packages}}"
        dest: "{{packages_dest}}"
    - name: install deb package
      become: true
      apt:
        deb: "{{packages_dest}}/{{deb_packages}}"
        state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install curl from rpm
  block:
    - name: copy rpm package
      copy:
        src: "files/{{rpm_packages}}"
        dest: "{{packages_dest}}"
    - name: install rpm package
      become: true
      yum:
        name: "{{packages_dest}}/{{rpm_packages}}"
        state: present
        disable_gpg_check: yes
  when: ansible_distribution == 'CentOS'

- name: create hw20 file info
  become: true
  template:
    src: "{{item}}"
    dest: /HW20_FILE_INFO
  loop:
    - templates/hw20.j2
