testfile:
  name: /opt/hw23_test_file
  mode: '644'
  state: touch
  newname: /opt/hw23_test_file_exists

testlink:
  src: /etc/hosts
  name: /opt/hw23_link
  newname: /opt/hw23_test_file_link
  state: link

packages_list:
  - nginx
  - docker-ce
  - docker-ce-cli
  - containerd.io

services_list:
  - nginx
  - docker

failtask:
  name1: "generate exit code 0"
  name2: "generate exit code 2"
