---
- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: restart docker
  become: true
  service:
    name: docker
    state: restarted
    enabled: yes
