Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "s1" do |s1|
    s1.vm.box = "ubuntu/focal64"
    s1.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "s2" do |s2|
    s2.vm.box = "centos/8"
    s2.vm.network "private_network", ip: "192.168.10.11"
  end
end
