Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "s1" do |s1|
    s1.vm.box = "ubuntu/focal64"
    s1.vm.network "private_network", ip: "192.168.10.10"
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
  end

  config.vm.define "s2" do |s2|
    s2.vm.box = "ubuntu/focal64"
    s2.vm.network "private_network", ip: "192.168.10.11"
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
  end
end
