Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "s1" do |s1|
    s1.vm.box = "ubuntu/trusty64"
    s1.vm.network "private_network", ip: "192.168.10.101"
    id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
    s1.vm.provision "copy ssh public key", type: "shell",
    inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
    config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
  end

  config.vm.define "s2" do |s2|
    s2.vm.box = "ubuntu/trusty64"
    s2.vm.network "private_network", ip: "192.168.10.102"
    id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
    s2.vm.provision "copy ssh public key", type: "shell",
    inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
    config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
  end

  config.vm.define "s3" do |s3|
    s3.vm.box = "ubuntu/trusty64"
    s3.vm.network "private_network", ip: "192.168.10.103"
    id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
    s3.vm.provision "copy ssh public key", type: "shell",
    inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
    config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
  end
end


