---
- name: add groups
  become: true
  group:
    name: "{{item}}"
    state: present
  loop: "{{user_groups}}"

- name: add users using loop
  become: true
  user:
    name: "{{item}}"
    home: "{{user_home}}/{{item}}"
    groups: "{{user_groups}}"
    shell: "{{user_shell}}"
    state: present
  loop:
    - hw22_1
    - hw22_2
