---
- name: create log service
  become: true
  template:
    src: "{{item.src}}"
    dest: "{{item.dst}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "{{mode}}"
  loop: "{{templatelist}}"
  notify:
    - start and enable service
    - logrotate task

- name: add users loop
  no_log: true
  import_tasks: adduserloop.yaml
  when: useraddmethod == "loop"

- name: add users with
  no_log: true
  import_tasks: adduserwith.yaml
  when: useraddmethod == "with"
