---
- name: create log service
  become: true
  template:
    src: "{{item.src}}"
    dest: "{{item.dst}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "{{mode}}"
  loop: "{{templatelist}}"
  notify:
    - start and enable service
