---
- name: create log service
  become: true
  template:
    src: "{{item.src}}"
    dest: "{{item.dst}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "{{mode}}"
  loop: "{{templatelist}}"
  notify:
    - start and enable service
    - logrotate task

- name: add users loop
  no_log: true
  import_tasks: adduserloop.yaml
  when: useraddmethod == "loop"

- name: add users with
  no_log: true
  import_tasks: adduserwith.yaml
  when: useraddmethod == "with"

- name: print password
  debug:
    msg: "{{password}}"

- name: save data locally
  lineinfile:
    path: "{{local_log_path}}"
    line: "{{ ansible_date_time.date }}"
    create: yes
  delegate_to: localhost

- name: save hostnames locally
  lineinfile:
    path: "{{local_log_path}}"
    line: "{{ inventory_hostname }}"
    create: yes
  delegate_to: localhost
